name: odoo-localdev

services:
  web:
    # image: soltec-odoo-desarrollo:1.0
    image: muevetec/soltec-odoo:1.0.6-dev
    depends_on:
      - database
    environment:
      HOST: ${DATABASE_HOST:-database}
      USER: ${DATABASE_USER:-odoo}
      PASSWORD: ${DATABASE_PASSWORD:-odoo}
    volumes:
      - ./extra-addons:/mnt/extra-addons
      - odoo-web-data:/var/lib/odoo
    ports:
      - "${ODOO_WEB_PORT:-8069}:8069"
    networks:
      - odoo-backend

  database:
    image: postgres:14
    environment:
      POSTGRES_DB:  ${DATABASE_NAME:-postgres}
      POSTGRES_USER: ${DATABASE_USER:-odoo}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-odoo}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - odoo-backend
    healthcheck:
      test: [
        "CMD-SHELL",
        "pg_isready",
        "-q",
        "-d", "${DATABASE_NAME:-database}",
        "-U", "${DATABASE_USER:-odoo}"
      ]
      retries: 3
      timeout: 5s
      interval: 15s
      start_period: 30s
      start_interval: 2s


volumes:
  odoo-web-data:
  postgres-data:


networks:
  odoo-backend:
