name: odoo-localdev

services:
  web:
    # build:
    #   context: .
    # image: soltec-odoo-desarrollo:1.0
    image: muevetec/soltec-odoo:1.0.6-dev
    depends_on:
      - database
    environment:
      HOST: ${DATABASE_HOST:-database}
      USER: ${DATABASE_USER:-odoo}
      PASSWORD: ${DATABASE_PASSWORD:-odoo}
    volumes:
      - ./extra-addons:/mnt/extra-addons
      - odoo-web-data:/var/lib/odoo
    ports:
      - "8069:8069"
    networks:
      - odoo-backend

  database:
    image: postgres:14
    environment:
      POSTGRES_DB:  ${DATABASE_NAME:-postgres}
      POSTGRES_USER: ${DATABASE_USER:-odoo}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-odoo}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - odoo-backend
    healthcheck:
      test: [
        "CMD-SHELL",
        "pg_isready",
        "-q",
        "-d", "${DATABASE_NAME:-database}",
        "-U", "${DATABASE_USER:-odoo}"
      ]
      retries: 3
      timeout: 5s
      interval: 15s
      start_period: 30s
      start_interval: 2s

  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@hola.com
  #     - PGADMIN_DEFAULT_PASSWORD=admin
  #   depends_on:
  #     - database
  #   ports:
  #     - "5050:80"
  #   networks:
  #     - odoo-backend
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin

volumes:
  odoo-web-data:
  postgres-data:
  # pgadmin-data:

networks:
  odoo-backend:
