# NOTE:
#
# Use either option [A] or [B]. Option [A] is enabled by default.
#
---
name: odoo-localdev

services:
  web:
    hostname: web
    # image: marvinsoftwaresolutions/odoo:local
    volumes:
      - odoo-web-data:/var/lib/odoo
      #
      # [A] Uncomment the following 2 mounted paths TO ONLY USE the addons
      # downloaded in localdev, ignoring the included in the image
      # - ./extra-addons:/mnt/extra-addons
      # - ./config/odoo/only_localdev_addons.odoo.conf:/etc/odoo/odoo.conf
      #
      # [B] Uncomment the following 2 mounted paths to use the addons
      # downloaded in localdev alongside the included in the image:
      # - ./extra-addons:/mnt/extra-addons/custom-addons
      # - ./config/odoo/odoo.conf:/etc/odoo/odoo.conf
      #
      # [C] Uncomment the following 2 mounted paths to use AFIP certificates
      # (need to be obtained following AFIP/ARCA instructions):
      # - ./certs/homologation.key:/mnt/certs/homologation.key
      # - ./certs/homologation.crt:/mnt/certs/homologation.crt
    ports:
      - "8069:8069"

volumes:
  odoo-web-data:
