# accessLog: {}
log:
  level: ERROR

api:
  dashboard: false
  insecure: false

providers:
  docker:
    exposedByDefault: false
    network: odoo-localdev_public
    defaultRule: Host(`{{ index .Labels "com.docker.compose.service" }}.{{ index .Labels "com.docker.compose.project" }}.${DOMAIN}`)
    endpoint: "unix:///var/run/docker.sock"

entrypoints:
  web:
    address: ":80"
    forwardedHeaders:
      trustedIPs:
        - 127.0.0.1/32
        - 172.16.0.0/12
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
    forwardedHeaders:
      trustedIPs:
        - 127.0.0.1/32
        - 172.16.0.0/12
